# Initial configuration for the Raspberry Pi that handles training cluster provisioning

- hosts: node2
  remote_user: pi
  become: yes
  become_method: sudo
  vars:
    host: node2
    ansible_become_pass: "raspberry" 
    ansible_ssh_pass: "raspberry" 

  roles:
  - first_setup


