# Initial configuration for the Raspberry Pi that handles training cluster provisioning

- hosts: node2
  remote_user: pi
  become: yes
  become_method: sudo
  vars:
    host: node2
    ansible_become_pass: raspberry 

  roles:
  - user_setup
  - worker_node

  tasks:
  - name: Configure the hostname
    block:
      - replace:
          dest: "/etc/hosts"
          regexp: "raspberrypi"
          replace: "{{ host }}"
      - hostname:
          name: "{{ host }}"

  - name: Reboot
    reboot:
