node_exporter_system_group: "node-exprtr"
node_exporter_system_user: "{{ node_exporter_system_group }}"

node_exporter_textfile_dir: "/var/lib/node_exporter"

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"

node_exporter_disabled_collectors: []
