# Setups worker node (master is also a worker node)
---
  - name: Install master node software 
    become: true
    apt: 
      update_cache: yes
      pkg:
        - vim
        - nmap
        - wget
        - curl
        - fail2ban

  - import_tasks: k3s.yml
    tags:
      - k3s_install     
