# Setups worker node (master is also a worker node)
---
 - name: Update all packages to latest within distro, then remove unneeded
   apt: 
     update_cache: yes 
     upgrade: dist

 - name: Configure timezone
   timezone:
     name: Europe/Warsaw

 - name: Install basic software 
   become: true
   apt: 
     update_cache: yes
     autoremove: yes
     pkg:
       - git
