#Tasks that are responsible for setting up Prometheus Node-Exporter
---
  - name: Check if node_exporter is installed
    stat:
      path: "/usr/local/bin/node_exporter"
    register: __node_exporter_is_installed
    check_mode: false
    tags:
      - node_exporter_install   

  - name: Gather currently installed node_exporter version (if any)
    command: "/usr/local/bin/node_exporter --version"
    args:
      warn: false
    changed_when: false
    register: __node_exporter_current_version_output
    check_mode: false
    when: __node_exporter_is_installed.stat.exists
    tags:
      - node_exporter_install

  - block:
      - name: Get latest release
        uri:
          url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
          method: GET
          return_content: true
          status_code: 200
          body_format: json
          validate_certs: false
        register: _latest_release
        until: _latest_release.status == 200
        retries: 5
    
      - name: "Set node_exporter version to {{ _latest_release.json.tag_name[1:] }}"
        set_fact:
          node_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
    
    delegate_to: localhost
    run_once: true

  - name: Create the node_exporter group
    become: true 
    group:
      name: "{{ node_exporter_system_group }}"
      state: present
      system: true
        
  - name: Create the node_exporter user
    become: true 
    user:
      name: "{{ node_exporter_system_user }}"
      groups: "{{ node_exporter_system_group }}"
      append: true
      shell: /usr/sbin/nologin
      system: true
      create_home: false
      home: /

  - block:
    - name: Download node_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false
      
    - name: Unpack node_exporter binary
      become: false
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-armv7/node_exporter"
      delegate_to: localhost
      check_mode: false
      
    - name: Propagate node_exporter binaries
      become: true 
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-armv7/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart node_exporter
      
  - name: Copy the Node Exporter systemd service file
    become: true 
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: 0644
    notify: restart node_exporter
    
  - name: Create textfile collector dir
    file:
      path: "{{ node_exporter_textfile_dir }}"
      state: directory
      owner: "{{ node_exporter_system_user }}"
      group: "{{ node_exporter_system_group }}"
      recurse: true
      mode: 0755
