# Setups worker node (master is also a worker node)
---
- name: Install basic software 
  become: true
  apt: 
    update_cache: yes
    autoremove: yes
    pkg:
      - git
      - golang

- import_tasks: node_exporter.yml
   
- import_tasks: k3s_preparation.yml
